---
- name: Copy dockerfile
  ansible.builtin.copy:
    src: files/dockerfile
    dest: /tmp/Dockerfile
    mode: "0644"
  register: mosquitto_dockerfile_copy

- name: Create backup script
  become: true
  ansible.builtin.copy:
    src: "files/backup.sh"
    dest: "/tmp/backup.sh"
    mode: "0644"
  register: mosquitto_backup_script_copy

- name: Build Docker image
  become: true
  community.docker.docker_image:
    name: "{{ mosquitto_backup_image_name }}"
    tag: "{{ mosquitto_backup_image_tag }}"
    source: build
    push: false
    build:
      path: /tmp
    force_source: "{{ mosquitto_dockerfile_copy.changed or mosquitto_backup_script_copy.changed }}"
    state: present
  notify: "Restart {{ mosquitto_service_name }}"

- name: Create backup .env file
  become: true
  ansible.builtin.template:
    src: templates/docker-compose/backup-toolkit.env.j2
    dest: "{{ mosquitto_service_config_dir }}/backup-toolkit.env"
    group: "{{ mosquitto_service_user }}"
    owner: "{{ mosquitto_service_user }}"
    mode: "0400"
  notify: "Restart {{ mosquitto_service_name }}"

- name: Create backup systemd service file
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.service.j2"
    dest: /etc/systemd/system/{{ mosquitto_service_name }}-backup.service
    owner: root
    group: root
    mode: "0644"
  register: mosquitto_backup_service

- name: Create backup systemd timer file
  become: true
  ansible.builtin.template:
    src: "templates/backup/backup.timer.j2"
    dest: /etc/systemd/system/{{ mosquitto_service_name }}-backup.timer
    owner: root
    group: root
    mode: "0644"
  vars:
    service: "{{ mosquitto_service_name }}"
    cron: "*-*-* 04:00:00"
  register: mosquitto_backup_timer

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: mosquitto_backup_service.changed or mosquitto_backup_timer.changed

- name: Enable and start backup timer
  become: true
  ansible.builtin.systemd:
    name: "{{ mosquitto_service_name }}-backup.timer"
    enabled: true
    state: started
  when: mosquitto_backup_service.changed or mosquitto_backup_timer.changed
