---
- name: Setup system
  ansible.builtin.include_tasks:
    file: setup.yml
    apply:
      tags:
        - setup
  tags:
    - always

- name: Setup mosquitto
  ansible.builtin.include_tasks:
    file: mosquitto.yml
    apply:
      tags:
        - mosquitto
  tags:
    - always

- name: Setup backup
  ansible.builtin.include_tasks:
    file: backup.yml
    apply:
      tags:
        - backup
  tags:
    - always
