---
- name: Create docker compose config
  become: true
  ansible.builtin.template:
    src: "templates/docker-compose/docker-compose.yml.j2"
    dest: "{{ mosquitto_service_config_dir }}/docker-compose.yml"
    owner: "{{ mosquitto_service_user }}"
    group: "{{ mosquitto_service_user }}"
    mode: "0644"
  notify: "Restart {{ mosquitto_service_name }}"

- name: Create systemd service file
  become: true
  ansible.builtin.template:
    src: "templates/{{ mosquitto_service_name }}/{{ mosquitto_service_name }}.service.j2"
    dest: /etc/systemd/system/{{ mosquitto_service_name }}.service
    owner: root
    group: root
    mode: "0644"
  notify: "Restart {{ mosquitto_service_name }}"
