---
- name: Create service user
  become: true
  ansible.builtin.user:
    name: "{{ mosquitto_service_user }}"
    create_home: false
    comment: "{{ mosquitto_service_user }} user with no shell access"
    shell: /bin/false

- name: Create config directory
  become: true
  ansible.builtin.file:
    path: "{{ mosquitto_service_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ mosquitto_service_user }}"
    group: "{{ mosquitto_service_user }}"

- name: Create data directory
  become: true
  ansible.builtin.file:
    path: "{{ mosquitto_service_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ mosquitto_service_user }}"
    group: "{{ mosquitto_service_user }}"

- name: Add users to docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - root
    - noxious
    - "{{ mosquitto_service_user }}"
